// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct holds the embedded dms server and the Wails application handle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckTools reports whether ffmpeg/ffprobe are on PATH so the UI can disable
 * transcoding/probing options when the tools are missing.
 */
export function CheckTools(): $CancellablePromise<$models.Tools> {
    return $Call.ByID(14851102).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDefaults returns sensible starting values for the form.
 */
export function GetDefaults(): $CancellablePromise<$models.Config> {
    return $Call.ByID(2724249329).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsAutoLaunchEnabled reports whether the app is registered to launch at login.
 * The OS autostart artifact (file or registry value) is the source of truth.
 */
export function IsAutoLaunchEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3723680322);
}

/**
 * IsRunning reports whether the embedded server is currently active.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1670839396);
}

/**
 * ListInterfaces returns the names of usable network interfaces for SSDP.
 */
export function ListInterfaces(): $CancellablePromise<string[]> {
    return $Call.ByID(3857048213).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LoadConfig returns the last saved form configuration, falling back to
 * GetDefaults when nothing has been saved yet (or the file is unreadable).
 */
export function LoadConfig(): $CancellablePromise<$models.Config> {
    return $Call.ByID(2822453907).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig persists the current form configuration so it can be restored on
 * the next launch. The write is atomic (temp file + rename).
 */
export function SaveConfig(cfg: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(3442292638, cfg);
}

/**
 * SelectDirectory opens a native folder picker and returns the chosen path.
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SelectIconFile opens a native picker limited to PNG images for the device icon.
 */
export function SelectIconFile(): $CancellablePromise<string> {
    return $Call.ByID(1422019494);
}

/**
 * ServerInfo reports the embedded dms version (no external binary needed).
 */
export function ServerInfo(): $CancellablePromise<string> {
    return $Call.ByID(2568429602);
}

/**
 * SetAutoLaunch registers or removes the OS autostart entry for this app.
 */
export function SetAutoLaunch(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(903093139, enable);
}

/**
 * StartServer builds and starts an in-process dms server from cfg. The server
 * runs in its own goroutine; lifecycle changes emit "dms:status" and all dms
 * log output is forwarded to the frontend via "dms:log".
 */
export function StartServer(cfg: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(1592333068, cfg);
}

/**
 * StopServer closes the embedded server, which unblocks its Run goroutine.
 */
export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(3845928010);
}

// Private type creation functions
const $$createType0 = $models.Tools.createFrom;
const $$createType1 = $models.Config.createFrom;
const $$createType2 = $Create.Array($Create.Any);
