// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config mirrors the dms command-line flags that the GUI exposes.
 */
export class Config {
    "path": string;
    "httpPort": string;
    "friendlyName": string;
    "ifname": string;
    "allowedIps": string;
    "deviceIcon": string;
    "ffprobeCachePath": string;
    "forceTranscodeTo": string;
    "ignoreHidden": boolean;
    "ignoreUnreadable": boolean;
    "noProbe": boolean;
    "noTranscode": boolean;
    "autoStartServer": boolean;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("httpPort" in $$source)) {
            this["httpPort"] = "";
        }
        if (!("friendlyName" in $$source)) {
            this["friendlyName"] = "";
        }
        if (!("ifname" in $$source)) {
            this["ifname"] = "";
        }
        if (!("allowedIps" in $$source)) {
            this["allowedIps"] = "";
        }
        if (!("deviceIcon" in $$source)) {
            this["deviceIcon"] = "";
        }
        if (!("ffprobeCachePath" in $$source)) {
            this["ffprobeCachePath"] = "";
        }
        if (!("forceTranscodeTo" in $$source)) {
            this["forceTranscodeTo"] = "";
        }
        if (!("ignoreHidden" in $$source)) {
            this["ignoreHidden"] = false;
        }
        if (!("ignoreUnreadable" in $$source)) {
            this["ignoreUnreadable"] = false;
        }
        if (!("noProbe" in $$source)) {
            this["noProbe"] = false;
        }
        if (!("noTranscode" in $$source)) {
            this["noTranscode"] = false;
        }
        if (!("autoStartServer" in $$source)) {
            this["autoStartServer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * Tools reports which external media tools are available on PATH. dms needs
 * ffprobe for media probing and ffmpeg for transcoding.
 */
export class Tools {
    "ffmpeg": boolean;
    "ffprobe": boolean;

    /** Creates a new Tools instance. */
    constructor($$source: Partial<Tools> = {}) {
        if (!("ffmpeg" in $$source)) {
            this["ffmpeg"] = false;
        }
        if (!("ffprobe" in $$source)) {
            this["ffprobe"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tools instance from a string or object.
     */
    static createFrom($$source: any = {}): Tools {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tools($$parsedSource as Partial<Tools>);
    }
}
