// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckTools():Promise<main.Tools>;

export function GetDefaults():Promise<main.Config>;

export function IsAutoLaunchEnabled():Promise<boolean>;

export function IsRunning():Promise<boolean>;

export function ListInterfaces():Promise<Array<string>>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectIconFile():Promise<string>;

export function ServerInfo():Promise<string>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function StartServer(arg1:main.Config):Promise<void>;

export function StopServer():Promise<void>;
