// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTools() {
  return window['go']['main']['App']['CheckTools']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function IsAutoLaunchEnabled() {
  return window['go']['main']['App']['IsAutoLaunchEnabled']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectIconFile() {
  return window['go']['main']['App']['SelectIconFile']();
}

export function ServerInfo() {
  return window['go']['main']['App']['ServerInfo']();
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
